Community/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),  # url의 우선순위는 먼저 넣은것이 사용된다.
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.mypage, name='mypage'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_id>/', views.user_page, name="user_page"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('<int:user_id>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name='password'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),

    path('<int:post_id>/comments/create/',
         views.comments_create, name='comments_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete/',
         views.comments_delete, name="comments_delete"),
    path('<int:post_id>/comments/<int:comment_id>/update/',
         views.comments_update, name="comments_update"),
    path('<int:post_id>/like/', views.post_like, name='post_like'),
    path('comments/<int:comment_id>/like',
         views.comment_like, name='comment_like'),
    path('hashtags/<int:tag_id>/', views.hashtag, name='hashtag')
]

Community/templates/base.html
{%load bootstrap4%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Community</title>
  {%bootstrap_css%}
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'posts:index' %}">COMMUNITY</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav d-flex justify-content-between" style="width:100%;">
        <div>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'posts:index'%}">전체글</a>
          </li>
        </div>

        <div class="d-lg-flex">
          {% if user.is_authenticated %}
          <li class="nav-item ">
            <a class="nav-link" href="{%url 'posts:create'%}">글쓰기</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{%url 'accounts:mypage'%}">{{user.username}}</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{%url 'accounts:logout'%}">로그아웃</a>
          </li>

          {% else%}

          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:signup'%}">회원가입</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:login'%}">로그인</a>
          </li>
          {% endif %}
        </div>
      </ul>
    </div>
  </nav>

  {%block body%}
  {%endblock%}

  {%bootstrap_javascript jquery='full'%}
  <script src="https://kit.fontawesome.com/2c6bfe5098.js" crossorigin="anonymous"></script>
</body>

</html>