Community/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),  # url의 우선순위는 먼저 넣은것이 사용된다.
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.mypage, name='mypage'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_id>/', views.user_page, name="user_page"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('<int:user_id>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name='password'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),

    path('<int:post_id>/comments/create/',
         views.comments_create, name='comments_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete/',
         views.comments_delete, name="comments_delete"),
    path('<int:post_id>/comments/<int:comment_id>/update/',
         views.comments_update, name="comments_update"),
    path('<int:post_id>/like/', views.post_like, name='post_like'),
    path('comments/<int:comment_id>/like',
         views.comment_like, name='comment_like'),
    path('hashtags/<int:tag_id>/', views.hashtag, name='hashtag')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.


class User(AbstractUser):
    followers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='followings')

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToFill


class Hashtag(models.Model):
    content = models.CharField(max_length=100)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField()
    post_img = ProcessedImageField(
        processors=[ResizeToFill(300, 300)],
        format='GIF',
        options={'quality': 90},
        upload_to='media')
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_posts')
    hashtags = models.ManyToManyField(Hashtag, related_name="posts")


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    comment_img = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_comments')
    hashtags = models.ManyToManyField(Hashtag, related_name="comments")

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
# settings.AUTH_USER_MODEL => 'accounts.User' 라는 스트링을 반환한다.


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()  # User 클래스. 이름에 구애받지 않는다.
        fields = ['first_name', 'last_name', 'email']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import User
# Create your views here.


@login_required
def mypage(req):
    user = req.user

    return render(req, 'accounts/mypage.html', {'user': user})


def signup(req):
    if req.user.is_authenticated:
        return redirect('posts:index')

    if req.method == 'POST':
        form = CustomUserCreationForm(req.POST)
        if form.is_valid():
            user = form.save()
            auth_login(req, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    return render(req, 'accounts/signup_form.html', {'form': form})


def login(req):
    if req.user.is_authenticated:
        return redirect('posts:index')

    if req.method == "POST":  # 인증만 하는 것이기 때문에 form.get_user로 유저 정보를 가져와야함
        form = AuthenticationForm(req, req.POST)
        if form.is_valid():
            auth_login(req, form.get_user())
            return redirect(req.GET.get('next') or 'posts:index')
    else:
        form = AuthenticationForm()

    return render(req, 'accounts/login_form.html', {'form': form})


def logout(req):
    auth_logout(req)
    return redirect('posts:index')


@login_required  # 포스트 요구 ? 로그인 요구 ?
def delete(req, user_id):
    target_user = get_object_or_404(User, id=user_id)
    user = req.user

    if target_user == user:
        user.delete()

    return redirect('posts:index')


@login_required
def update(req):
    if req.method == 'POST':
        form = CustomUserChangeForm(req.POST, instance=req.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:mypage')
    else:
        form = CustomUserChangeForm(instance=req.user)

    return render(req, 'accounts/form.html', {'form': form})


def password(req):
    if req.method == "POST":
        form = PasswordChangeForm(req.user, req.POST)
        if form.is_valid():
            user = form.save()
            # 비밀번호가 변경되면 자동으로 로그아웃된다.
            update_session_auth_hash(req, user)  # 자동 로그아웃을 방지
            return redirect('accounts:mypage')
    else:
        form = PasswordChangeForm(req.user)

    return render(req, 'accounts/form.html', {'form': form})


def user_page(req, user_id):
    search_user = get_object_or_404(User, id=user_id)

    # 본인은 마이페이지로.
    if req.user == search_user:
        return redirect('accounts:mypage')

    return render(req, 'accounts/user_page.html', {'search_user': search_user})


@login_required
def follow(req, user_id):
    target_user = get_object_or_404(User, id=user_id)
    user = req.user

    if target_user != user:
        if target_user in user.followings.all():
            user.followings.remove(target_user)
        else:
            user.followings.add(target_user)

    return redirect('accounts:user_page', user_id)

accounts/templates/accounts/form.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% load socialaccount %}
{% load static %}
{%block body%}
<div class="container my-5" style="max-width: 500px;">
  <div class="p-4" style="border: 1px solid rgba(0,0,0,0.1); border-radius:5px;">
    <form action="" method="post">
      {%csrf_token%}
      {%bootstrap_form form%}
      <div class="text-center mb-3">
        <input class="btn btn-dark" type="submit" value="로그인">
      </div>
    </form>
  </div>
</div>
{%endblock%}

accounts/templates/accounts/login_form.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% load socialaccount %}
{% load static %}
{%block body%}
<div class="container my-5" style="max-width: 500px;">
  <div class="p-4" style="border: 1px solid rgba(0,0,0,0.1); border-radius:5px;">
    <form action="" method="post">
      {%csrf_token%}
      {%bootstrap_form form%}
      <div class="text-center mb-3">
        <input class="btn btn-dark" type="submit" value="로그인">
      </div>
    </form>
    <hr>
    <div class="text-center">
      <h6 class="text-center">계정이 없으신가요? <a href="{% url 'accounts:signup' %}">회원가입</a></h6>
      <h6 class="font-weight-bolder text-muted" style="font-size: 0.8rem;">또는</h6>
      <a href="{% provider_login_url 'kakao' %}"><img src="{% static 'kakao_login.png' %}" alt=""></a>
    </div>
  </div>
</div>
{%endblock%}

accounts/templates/accounts/mypage.html
{%extends 'base.html'%}
{% load humanize %}
{%block body%}
<div class="container my-5">

  <h1 class="mb-3 text-center">👋 {{user.username}}</h1>
  <h5 class="text-center text-muted">{{user.email}}</h5>
  <h6 class="text-center">{{user.last_name}}{{user.first_name}}</h6>

  <div class="d-flex align-items-center my-3 justify-content-center">
    <a class="btn btn-sm btn-warning mr-3" href="{% url 'accounts:update' %}">정보수정</a>
    <a class="btn btn-sm btn-warning mr-3" href="{% url 'accounts:password' %}">비밀번호변경</a>
    <form action="{% url 'accounts:delete' user.id %}" method="POST">
      {%csrf_token%}
      <input class="btn btn-sm btn-danger mr-3" type="submit" value="회원탈퇴">
    </form>
  </div>

  <div class="d-flex justify-content-center py-3 mb-4">
    <div class="btn-group mr-3">
      <button class="btn btn-primary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        팔로잉 ({{user.followings.all|length}})
      </button>
      <div class="dropdown-menu text-center p-3">
        {% for following in user.followings.all %}
        <h5 class="text-center font-weight-bold"><a class="text-dark" style="text-decoration: none;"
            href="{% url 'accounts:user_page' following.id%}">{{following.username}}</a></h5>
        {% empty %}
        <h6>팔로잉이 없습니다.</h6>
        {% endfor %}
      </div>
    </div>

    <div class="btn-group">
      <button class="btn btn-success btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        팔로워 ({{user.followers.all|length}})
      </button>
      <div class="dropdown-menu text-center p-3">
        {% for follower in user.followers.all %}
        <h5 class="text-center font-weight-bold"><a class="text-dark" style="text-decoration: none;"
            href="{% url 'accounts:user_page' follower.id%}">{{follower.username}}</a></h5>
        {% empty %}
        <h6>팔로워가 없습니다.</h6>
        {% endfor %}
      </div>
    </div>
  </div>

  <h2 class="my-3">📝 나의 POST [{{user.post_set.count}}]</h2>
  <hr>

  <div class="my-4">
    <div class="row">
      {% for post in user.post_set.all %}
      {% include 'posts/_post_card.html' %}
      {% endfor %}
    </div>
  </div>

  <h2 class="my-4">👍 나의 따봉 포스트 [{{user.like_posts.count}}]</h2>
  <hr>
  <div class="row">
    {% for post in user.like_posts.all%}
    {% include 'posts/_post_card.html' %}
    {%endfor%}
  </div>

  <h2 class="my-3">💬 나의 COMMENT [{{user.comment_set.count}}]</h2>
  <hr>

  <div class="my-4">
    {% for comment in user.comment_set.all %}
    <div class="d-flex">
      <h6 class="mr-3">{{comment.created_at|naturaltime}}</h6>
      <h5>
        <a href="{% url 'posts:detail' comment.post.id%}" class="text-dark  font-weight-bold"
          style="text-decoration: none;">
          {{comment.content}}
        </a>
      </h5>
    </div>
    {% endfor %}
  </div>

  <h2 class="my-4">📑 나의 따봉 코멘트 [{{user.like_comments.count}}]</h2>
  <hr>
  {% for comment in user.like_comments.all%}
  <h5><a class="text-dark font-weight-bold" style="text-decoration:none;"
      href="{%url 'posts:detail' comment.post.id%}">{{comment.content}}</a></h5>
  {%endfor%}

</div>


{%endblock%}

accounts/templates/accounts/signup_form.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{% load socialaccount %}
{% load static %}

{%block body%}
<div class="container my-5" style="max-width: 500px;">
  <h3 class="text-center my-4 font-weight-bold">회원가입</h3>
  <div class="p-4" style="border: 1px solid rgba(0,0,0,0.1); border-radius:5px;">
    <form action="" method="post">
      {%csrf_token%}
      {%bootstrap_form form%}
      <div class="text-center mb-3">
        <input class="btn btn-dark" type="submit" value="작성완료">
      </div>
    </form>
    <hr>
    <h6 class="text-center">이미 계정이 있으신가요? <a href="{% url 'accounts:login' %}">로그인</a></h6>
  </div>
</div>
{%endblock%}

accounts/templates/accounts/user_page.html
{% extends 'base.html' %}
{% load humanize%}
{% block body %}
<div class="container my-5">
  <div class="d-flex align-items-center justify-content-between">
    <h1>🍧 {{search_user.username}}</h1>
    {%if user.is_authenticated and user != search_user %}
    {% if search_user in user.followings.all %}
    <div>
      <a class="btn btn-sm btn-danger" href="{% url 'accounts:follow' search_user.id %}">🖕 언팔로우</a>
    </div>
    {% else%}
    <div>
      <a class="btn btn-sm btn-primary" href="{% url 'accounts:follow' search_user.id %}">🦅 팔로우</a>
    </div>
    {% endif%}
    {% endif%}
  </div>
  <hr>
  <!-- following / follower -->
  <div class="text-center mb-3">
    <div class="btn-group mr-3">
      <button class="btn btn-primary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        팔로잉 ({{search_user.followings.all|length}})
      </button>
      <div class="dropdown-menu text-center p-3">
        {% for following in search_user.followings.all %}
        <h5 class="text-center font-weight-bold"><a class="text-dark" style="text-decoration: none;"
            href="{% url 'accounts:user_page' following.id%}">{{following.username}}</a></h5>
        {% empty %}
        <h6>팔로잉이 없습니다.</h6>
        {% endfor %}
      </div>
    </div>

    <div class="btn-group">
      <button class="btn btn-success btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        팔로워 ({{search_user.followers.all|length}})
      </button>
      <div class="dropdown-menu text-center p-3">
        {% for follower in search_user.followers.all %}
        <h5 class="text-center font-weight-bold"><a class="text-dark" style="text-decoration: none;"
            href="{% url 'accounts:user_page' follower.id%}">{{follower.username}}</a></h5>
        {% empty %}
        <h6>팔로워가 없습니다.</h6>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="row">
    {% for post in search_user.post_set.all %}
    {% include 'posts/_post_card.html' %}
    {% endfor %}
  </div>


  {% endblock %}