Community/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),  # url의 우선순위는 먼저 넣은것이 사용된다.
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.mypage, name='mypage'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_id>/', views.user_page, name="user_page"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
    path('<int:user_id>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name='password'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),

    path('<int:post_id>/comments/create/',
         views.comments_create, name='comments_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete/',
         views.comments_delete, name="comments_delete"),
    path('<int:post_id>/comments/<int:comment_id>/update/',
         views.comments_update, name="comments_update"),
    path('<int:post_id>/like/', views.post_like, name='post_like'),
    path('comments/<int:comment_id>/like',
         views.comment_like, name='comment_like'),
    path('hashtags/<int:tag_id>/', views.hashtag, name='hashtag')
]

posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToFill


class Hashtag(models.Model):
    content = models.CharField(max_length=100)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField()
    post_img = ProcessedImageField(
        processors=[ResizeToFill(300, 300)],
        format='GIF',
        options={'quality': 90},
        upload_to='media')
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_posts')
    hashtags = models.ManyToManyField(Hashtag, related_name="posts")


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    comment_img = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_comments')
    hashtags = models.ManyToManyField(Hashtag, related_name="comments")

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    title = forms.CharField(label='제목')
    content = forms.CharField(widget=forms.Textarea, label='내용')

    class Meta:
        model = Post
        fields = ['title', 'content', 'post_img']


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="", help_text="🤬 악플은 지양해주세요", widget=forms.TextInput(attrs={'placeholder': "댓글을 써주세요"}))
    comment_img = forms.CharField(required=False,
                                  label="", help_text="이미지 주소를 넣어주세요", widget=forms.TextInput(attrs={'placeholder': "IMAGE URL(필수는 아니에요)"}))

    class Meta:
        model = Comment
        fields = ['content', 'comment_img']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from .models import Post, Comment, Hashtag
from django.core.paginator import Paginator
import random
from django.http import JsonResponse
# Create your views here.

# Utility fn


def hashtagging(obj):
    for word in obj.content.split():
        if word.startswith('#'):
            hashtag, created = Hashtag.objects.get_or_create(
                content=word)
            obj.hashtags.add(hashtag)

# routes


def index(req):
    posts = Post.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 12)

    page = req.GET.get('page')
    posts = paginator.get_page(page)
    return render(req, 'posts/index.html', {'posts': posts})


@login_required
def create(req):
    user = req.user
    if req.method == "POST":
        form = PostForm(req.POST, req.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = user
            post.save()

            # 해시태그 작업 (구체적인 방법은 수정 필요.)
            hashtagging(post)

            return redirect('posts:index')
    else:
        form = PostForm()
    return render(req, 'posts/form.html', {'form': form})


def detail(req, post_id):
    post = get_object_or_404(Post, id=post_id)
    comment_form = CommentForm()
    return render(req, 'posts/detail.html', {'post': post, 'comment_form': comment_form})


def update(req, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = req.user

    if post.user != user:
        return redirect('posts:detail', post_id)
    else:
        if req.method == "POST":
            form = PostForm(req.POST, req.FILES, instance=post)
            if form.is_valid():
                post = form.save()
                # 해시태그 재작업 필요함
                post.hashtags.clear()
                hashtagging(post)

                return redirect('posts:detail', post_id)
        else:
            form = PostForm(instance=post)

        return render(req, 'posts/form.html', {'form': form})


def delete(req, post_id):
    post = get_object_or_404(Post, id=post_id)

    if post.user != req.user:
        return redirect('posts:detail', post_id)
    else:
        post.delete()

    return redirect('posts:index')


def comments_create(req, post_id):
    post = get_object_or_404(Post, id=post_id)

    if req.user.is_authenticated:
        user = req.user
        if req.method == "POST":
            form = CommentForm(req.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.user = user
                comment.save()

                # 해시태그 작업
                hashtagging(comment)

                return redirect('posts:detail', post_id)
    else:
        return redirect('posts:detail', post_id)


def comments_delete(req, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if req.user == comment.user:
        comment.delete()

    return redirect('posts:detail', post_id)


def comments_update(req, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if req.user == comment.user:

        if req.method == "POST":
            form = CommentForm(req.POST, instance=comment)
            if form.is_valid():
                form.save()
                comment.hashtags.clear()
                hashtagging(comment)
                return redirect('posts:detail', post_id)
        else:
            form = CommentForm(instance=comment)

        return render(req, 'posts/form.html', {'form': form})
    else:
        return redirect('posts:detail', post_id)


@login_required
def post_like(req, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = req.user

    if user in post.like_users.all():
        post.like_users.remove(user)
        is_post_liked = False
    else:
        post.like_users.add(user)
        is_post_liked = True

    post_like_count = post.like_users.all().count()

    context = {
        'is_post_liked': is_post_liked,
        'post_like_count': post_like_count
    }

    return JsonResponse(context)


@login_required
def comment_like(req, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    user = req.user

    if comment.like_users.filter(id=user.id):
        comment.like_users.remove(user)
        is_comment_liked = False
    else:
        comment.like_users.add(user)
        is_comment_liked = True

    comment_like_count = comment.like_users.all().count()
    context = {
        'is_comment_liked': is_comment_liked,
        'comment_like_count': comment_like_count
    }

    return JsonResponse(context)


def hashtag(req, tag_id):
    hashtag = get_object_or_404(Hashtag, id=tag_id)

    return render(req, 'posts/hashtag.html', {'hashtag': hashtag})

posts/templates/posts/_comments.html
{% load make_link %}

{% for comment in post.comment_set.all%}
<div class="d-flex justify-content-between align-items-center">
  <h6 class="text-muted mx-2">{{comment.user.username}} <span class="comment-like-count"
      data-id="{{comment.id}}">{{comment.like_users.all.count}}</span></h6>
  <div class="d-flex align-items-center">
    {% if user.is_authenticated %}
    {% if user in comment.like_users.all %}
    <button class="btn btn-sm btn-danger mr-1 comment-like" data-id="{{comment.id}}">
      좋아요취소
    </button>
    {% else %}
    <button class="btn btn-sm btn-primary mr-1 comment-like" data-id="{{comment.id}}">
      좋아요
    </button>
    {% endif %}
    {% endif %}

    {% if request.user == comment.user %}
    <form class="mr-1" action="{%  url 'posts:comments_delete' post.id comment.id%}" method="post">
      {%csrf_token%}
      <input type="submit" class="btn btn-dark btn-sm" value="🗑️">
    </form>
    <a class="btn btn-sm btn-warning" href="{% url 'posts:comments_update' post.id comment.id %}">✏️</a>
    {% endif%}

  </div>
</div>
<div class="d-flex justify-content-between my-1">
  <div class="d-flex justify-content-between align-items-center">
    <div class="mr-2"
      style="background-image: url({{comment.comment_img}});width:75px;height:75px;background-position:center;background-size:cover; background-color:white; border-radius:10px;">
    </div>
    <h6>{{comment|hashtag_link|safe}}</h6>
  </div>
</div>
<hr style="border: 1px solid rgba(0,0,0,0.1);">
{%endfor%}

<script>
  const commentLikeBtns = document.querySelectorAll('.comment-like')
  commentLikeBtns.forEach(button => button.addEventListener('click', e => {
    const {
      id: commentId
    } = e.target.dataset
    const commentLikeBtn = document.querySelector(`.comment-like[data-id="${commentId}"]`)
    const commentLikeCount = document.querySelector(`.comment-like-count[data-id="${commentId}"]`)

    axios.get(`/posts/comments/${commentId}/like`)
      .then(res => {

        const {
          comment_like_count,
          is_comment_liked
        } = res.data

        commentLikeCount.innerText = comment_like_count
        if (is_comment_liked) {
          commentLikeBtn.innerText = '좋아요취소'
          commentLikeBtn.classList.remove('btn-primary')
          commentLikeBtn.classList.add('btn-danger')
        } else {
          commentLikeBtn.innerText = '좋아요'
          commentLikeBtn.classList.remove('btn-danger')
          commentLikeBtn.classList.add('btn-primary')
        }
      })
      .catch(err => console.log(err))
  }))
</script>

posts/templates/posts/_post_card.html
<div class="col-12 col-md-6 col-lg-4 my-2">
  <a class="text-dark" href="{% url 'posts:detail' post.id%}" style="text-decoration: none;">
    <img src="{{post.post_img.url}}" alt="" style="object-fit: cover;width:100%; border:1px solid rgba(0,0,0,0.1)">
  </a>
</div>

posts/templates/posts/detail.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% load make_link %}
{%block body%}
<div class="container my-5">
  <div class="d-flex justify-content-between align-items-center">
    <h2 class="mb-3 font-weight-bold">{{post.title}}</h2>
    {%if request.user == post.user %}
    <div class="d-flex justify-content-end">
      <div>
        <a class="btn btn-warning btn-sm mr-2" href="{%url 'posts:update' post.id%}">수정</a>
      </div>
      <form action="{%url 'posts:delete' post.id%}" method="POST">
        {%csrf_token%}
        <input class="btn btn-danger btn-sm" type="submit" value="삭제">
      </form>
    </div>
    {%endif%}
  </div>
  <div class="d-flex">
    <h6 class="m-0 mr-3">👤 <a href="{% url 'accounts:user_page' post.user.id%}"
        style="text-decoration: none;">{{post.user.username}}</a></h6>
    <h6 class="text-muted m-0 mr-3">📅 {{post.created_at}}</h6>
  </div>

  <hr style="border: 2px solid rgba(0,0,0,.1);">
  <div class="text-center">
    <img src="{{post.post_img.url}}">
  </div>
  <p class="my-5" style="min-height: 100px;">{{post|hashtag_link|safe}}</p>
  <div class="text-center my-5">
    {% if user.is_authenticated %}
    <button data-id="{{post.id}}" class="like-btn btn">
      {% if user in post.like_users.all %}
      <i data-id="{{post.id}}" class="fas fa-thumbs-up"><span data-id="{{post.id}}"
          class="like-count ml-2">{{post.like_users.count}}</span></i>
      {% else %}
      <i data-id="{{post.id}}" class="far fa-thumbs-up"><span data-id="{{post.id}}"
          class="like-count ml-2">{{post.like_users.count}}</span></i>
      {% endif %}
      {% endif %}
    </button>
  </div>

  <hr style="border: 2px solid rgba(0,0,0,.1);">
  <h6>💬 COMMENT</h6>
  {% if user.is_authenticated %}
  <form class="my-3" action="{% url 'posts:comments_create' post.id%}" method="post">
    {%csrf_token%}
    {%bootstrap_form comment_form%}
    <div class="d-flex justify-content-end">
      <input type="submit" class="btn btn-dark btn-sm" value="댓글달기">
    </div>
  </form>
  {% else %}
  <h6 class="text-center">댓글을 남기려면 <a href="{% url 'accounts:login' %}">로그인</a></h6>
  {% endif%}

  <hr>
  {% include 'posts/_comments.html' %}

</div>

<script>
  const likeBtn = document.querySelector('.like-btn')
  const likeIcon = document.querySelector('.fa-thumbs-up')
  likeBtn.addEventListener('click', (e) => {
    const postId = e.target.dataset.id
    const likeCount = document.querySelector(`.like-count[data-id="${postId}"]`)
    axios.get(`/posts/${postId}/like/`)
      .then(res => {
        const {
          is_post_liked,
          post_like_count
        } = res.data

        // 카운트 변경
        likeCount.innerText = post_like_count

        // 아이콘 변경
        if (is_post_liked) {
          likeIcon.classList.remove('far')
          likeIcon.classList.add('fas')
        } else {
          likeIcon.classList.remove('fas')
          likeIcon.classList.add('far')
        }

      })
      .catch(err => console.log(err))
  })
</script>

{%endblock%}

posts/templates/posts/form.html
{%extends 'base.html'%}
{%load bootstrap4%}
{%block body%}
<div class="container my-5">
  <form action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {%bootstrap_form form%}
    <input class="btn btn-dark" type="submit" value="제출">
  </form>
</div>
{%endblock%}

posts/templates/posts/hashtag.html
{% extends 'base.html' %}
{% block body%}
<div class="container my-5">
  <h1>{{hashtag.content}}</h1>
  <hr>
  <div class="row">
    {% for post in hashtag.posts.all %}
    {% include 'posts/_post_card.html' %}
    {% endfor %}
  </div>
</div>
{% endblock %}

posts/templates/posts/index.html
{%extends 'base.html'%}
{% load humanize %}
{% load bootstrap_pagination %}
{%block body%}
<div class="container my-5">
  <!-- page title -->
  <h1 class="my-3">📝 POSTS</h1>
  <hr>
  <!-- post cards -->
  <div class="row">
    {% for post in posts %}
    <div class="col-12 col-md-6 col-lg-4 my-2">
      <div class="card-deck">
        <div class="card">
          <a href="{% url 'posts:detail' post.id%}">
            {% if post.post_img.url == ''%}
            <img src="http://www.wikitree.co.kr/webdata/editor/201909/23/img_20190923154844_113f6f66.jpg"
              class="card-img-top" style="min-height:15rem;max-height:15rem; height:100%;object-fit:cover;">
            {% else%}
            <img src="{{post.post_img.url}}" class="card-img-top"
              style="min-height:15rem;max-height:15rem; height:100%;object-fit:cover;">
            {%endif%}
          </a>

          <div class="card-body">
            <a href="{% url 'posts:detail' post.id%}" style="text-decoration: none;color:black;">
              <h5 class="card-title m-0 font-weight-bold">{{post.title}} [{{post.comment_set.count}}]</h5>
            </a>
          </div>
          <div class="card-footer d-flex justify-content-between">
            <small class="text-muted">👤 <a href="{% url 'accounts:user_page' post.user.id%}"
                style="text-decoration: none;">{{post.user.username}}</a></small>
            <small class="text-muted">👍 {{post.like_users.count}}</small>
            <small class="text-muted">⌛ {{post.created_at|naturaltime}}</small>
          </div>
        </div>
      </div>
    </div>
    {% empty %}
    <h1 class="text-center">첫 번째 글을 남겨보세요!</h1>
    {% endfor %}
  </div>

  <!-- pagination -->
  <div class="d-flex justify-content-center my-3">
    {% bootstrap_paginate posts %}
  </div>
</div>
{%endblock%}